# Generated by Django 3.2.9 on 2022-04-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateOfEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dateOfStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
